[workspace]
members = [
    "compute_tools",
    "control_plane",
    "pageserver",
    "proxy",
    "safekeeper",
    "workspace_hack",
    "zenith",
    "libs/*",
]

[profile.release]
# This is useful for profiling and, to some extent, debug.
# Besides, debug info should not affect the performance.
debug = true

# This is only needed for proxy's tests.
# TODO: we should probably fork `tokio-postgres-rustls` instead.
[patch.crates-io]
tokio-postgres = { git = "https://github.com/zenithdb/rust-postgres.git", rev="2949d98df52587d562986aad155dd4e889e408b7" }
